# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voronoi_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.diagram_widget = diagramWidget(self.centralwidget)
        self.diagram_widget.setGeometry(QtCore.QRect(80, 20, 621, 651))
        self.diagram_widget.setObjectName("diagram_widget")
        self.next_case_Button = QtWidgets.QPushButton(self.centralwidget)
        self.next_case_Button.setGeometry(QtCore.QRect(730, 280, 151, 51))
        self.next_case_Button.setObjectName("next_case_Button")
        self.next_step_Button = QtWidgets.QPushButton(self.centralwidget)
        self.next_step_Button.setGeometry(QtCore.QRect(730, 370, 151, 51))
        self.next_step_Button.setObjectName("next_step_Button")
        self.messageLabel = QtWidgets.QLabel(self.centralwidget)
        self.messageLabel.setGeometry(QtCore.QRect(730, 60, 301, 181))
        self.messageLabel.setText("")
        self.messageLabel.setObjectName("messageLabel")
        self.run_Button = QtWidgets.QPushButton(self.centralwidget)
        self.run_Button.setGeometry(QtCore.QRect(730, 460, 151, 51))
        self.run_Button.setObjectName("run_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionOpenPoint = QtWidgets.QAction(MainWindow)
        self.actionOpenPoint.setObjectName("actionOpenPoint")
        self.actionOpenDiagram = QtWidgets.QAction(MainWindow)
        self.actionOpenDiagram.setObjectName("actionOpenDiagram")
        self.actionSave_Diagram = QtWidgets.QAction(MainWindow)
        self.actionSave_Diagram.setObjectName("actionSave_Diagram")
        self.menuOpen.addAction(self.actionOpenPoint)
        self.menuOpen.addAction(self.actionOpenDiagram)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionSave_Diagram)
        self.menuSetting.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_case_Button.setText(_translate("MainWindow", "Next Case"))
        self.next_step_Button.setText(_translate("MainWindow", "Next Step"))
        self.run_Button.setText(_translate("MainWindow", "Run"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionOpenPoint.setText(_translate("MainWindow", "Point"))
        self.actionOpenDiagram.setText(_translate("MainWindow", "Diagram"))
        self.actionSave_Diagram.setText(_translate("MainWindow", "Save_Diagram"))
from diagramwidget import diagramWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
